export const Layout = {
  gutter: 20,
  afterStatusBar: 8,
  afterHomeIndicator: 8,
  tabBarTop: 8,
  tabItemMinHeight: 48,
  buttonHeight: 52,
  buttonRadius: 16,
  iconButton: 44,
  iconRadius: 14,
  pillHeight: 36,
  pillRadius: 16,
  fieldHeight: 48,
  fieldRadius: 16,
};
